{"name": "登录异常，测试数据是:{'accounts': '', 'pwd': 'yaoyao', 'exp': '登录账号有误'}", "status": "passed", "description": "\n        对登录接口进行异常登录的测试\n        :param args: 参数化的数据\n        :return:\n        ", "attachments": [{"name": "log", "source": "56cdeb2c-be0e-491f-aa33-cd7be1914ce8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "args", "value": "{'accounts': '', 'pwd': 'yaoyao', 'exp': '登录账号有误'}"}], "start": 1621316118262, "stop": 1621316118380, "uuid": "3e6d890e-3324-4015-a60e-4c11877a6948", "historyId": "ff1d27090ef74452512974d50f385b0f", "testCaseId": "acfd50c72596b11b4392c40d7652bccf", "fullName": "script.test_login.TestLogin#test_login_error", "labels": [{"name": "story", "value": "异常数据的登录接口测试"}, {"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-ISSK6DL4"}, {"name": "thread", "value": "13248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}]}